version: 2

builds:
  - id: todoist-cli
    main: ./cmd/todoist-cli
    binary: todoist-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    name_template: "todoist-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

brews:
  - name: todoist-cli
    repository:
      owner: nyactl
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/nyactl/todoist-cli"
    description: "Todoist CLI"
    license: "MIT"
    install: |
      bin.install "todoist-cli" => "td"
    test: |
      system "#{bin}/td", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
