version: 2

builds:
  - id: todoist-cli
    main: ./cmd/todoist-cli
    binary: todoist-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: default
    name_template: "todoist-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

nfpms:
  - package_name: todoist-cli
    homepage: "https://github.com/nyactl/todoist-cli"
    maintainer: "nyactl <noreply@github.com>"
    description: "Fast, minimal Todoist CLI with a local SQLite cache"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin


brews:
  - name: todoist-cli
    directory: Formula
    skip_upload: auto
    repository:
      owner: nyactl
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/nyactl/todoist-cli"
    description: "Fast, minimal Todoist CLI with a local SQLite cache"
    license: "MIT"
    install: |
      bin.install "todoist-cli"
    test: |
      system "#{bin}/todoist-cli", "--version"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
